### PR TITLE
Update reference URI

### PR DESCRIPTION
**Pull request by mbl-eea-sk**
Reference URI updated according to #7

### CODE REVIEW

**Comment by mbl-eea-sk** [comment]
Test plese

**Comment by jindrichmynarz** [comment]
This works as expected, but the issue #8 reappears. Will it be gone after merge?

**Comment by mbl-eea-sk** [comment]
Changed to up-to-date version, retest please

**Comment by jindrichmynarz** [comment]
In the current version `<http://purl.org/procurement/public-contracts#attachment>` property is replaced by  `<http://reference.data.gov.uk/def/payment#Payment>` (a class). This is a regression back to #8.

**Comment by mbl-eea-sk** [comment]
Now I got lost :) is it OK now or should it be some other way yet?

**Comment by jindrichmynarz** [comment]
It's not OK. The problem is that now #8 is not fixed, since instead of using `<http://purl.org/procurement/public-contracts#attachment>` property for `vyska-pomoci` the output uses `<http://reference.data.gov.uk/def/payment#Payment>` (which does not make sense, because it's a class and not a property). I think there was some mix-up.

To sum up:
- Documents should be linked via `<http://purl.org/procurement/public-contracts#attachment>` (as per #8).
- Resources should instantiate `<http://reference.data.gov.uk/def/payment#Payment>` (as per #7).

**Comment by jindrichmynarz** [comment]
@mbl-eea-sk, if needed, you can contact me on Skype for more clarifications. I'm jindrich.mynarz.

**Pull request merged**
